### ISSUE TITLE
gene_id annotation

### ISSUE THREAD

**Issue by morellr** [Magdoll/images_public#1]
sqanti_qc2 (v.7.3.2) no longer substitutes overlapping gene_id from the reference annotation gtf in the the gene_id field of the  *.collapsed.gff file -- they all are "PB.*". It is very helpful to have this annotation, could you please restore this function?

Also, if the annotated gene_id field could be propagated to the *.filtered_lite.gtf created by sqanti_filter2, that would be great also!

**Comment by Magdoll** [comment]
Hi,
please file this under [SQANTI2 issues](https://github.com/Magdoll/SQANTI2/issues)
and i'll make it a feature request
thanks!
